mode: train
seed: 32
validation_frequency: 5
epochs: 20
batch_size: 4
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 256
val_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 256
model: 
  name: efficientnet-b7
  pred_type: regression
  tuning_type: fine-tuning
  pre_trained_path: b7_3
  weight_type: best_val_roc
  hyper_params:
    batch_norm_momentum: 0.99
optimiser: 
  name: AdamW
  hyper_params:
    learning_rate: 0.001
scheduler:
  name: CosineAnnealingLR
  hyper_params:
    T_max: 20
    eta_min: 0.0000001
    last_epoch: -1
loss_function: 
  name: mean-squared-error-loss
