mode: train
seed: 1024
validation_frequency: 2
epochs: 50
batch_size: 4
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 456
  transform: policy
val_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 456
model: 
  name: efficientnet-b5
  pred_type: classification
  tuning_type: fine-tuning
  hyper_params:
    fc_drop_out: 0.5
optimiser: 
  name: Adam
  hyper_params:
    learning_rate: 0.001
    weight_decay: 0.0001
scheduler:
  name: cosineAnnealing-warmup-lr
loss_function: 
  name: cross-entropy-loss
