mode: test
seed: 512
test_dataset: 
  name: fgvc7
  resize_dims: 545
ensemble: False
num_classes: 4
experiment_list:
  # - experiment:
  #     path: exp_26_a
  #     weight_type: best_val_kaggle_metric
  # - experiment:
  #     path: exp_26_b
  #     weight_type: best_val_kaggle_metric
  - experiment:
      path: exp_26_d
  - experiment:
      path: exp_26_e