mode: test
test_dataset: 
  name: fgvc7
  resize_dims: 224
ensemble: False
num_classes: 4
experiment_list:
  - experiment:
      path: train_dnet161_224
      weight_type: best_val_loss
  - experiment:
      path: train_dnet161_224_pr_fe
      weight_type: best_val_loss