seed: 2020
mode: train
validation_frequency: 5
epochs: 30
batch_size: 2
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 512
val_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 512
model: 
  name: efficientnet-b7
  pred_type: regression
  tuning_type: feature-extraction
  hyper_params:
    batch_norm_momentum:  0.99
  pre_trained_path: train_b7_224
  weight_type: best_val_roc
optimiser: 
  name: AdamW
  hyper_params:
    learning_rate: 0.001
scheduler:
  name: CosineAnnealingLR
  hyper_params:
    T_max: 30
    eta_min: 0.0000001
    last_epoch: -1
loss_function: 
  name: mean-squared-error-loss
