seed: 32
mode: train
validation_frequency: 2
epochs: 20
batch_size: 16
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 224
val_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 224
model: 
  name: efficientnet-b7
  pred_type: regression
  tuning_type: feature-extraction
  hyper_params:
    batch_norm_momentum:  0.99
  pre_trained_path: train_b7_224_cnt
  weight_type: best_val_roc
optimiser: 
  name: AdamW
  hyper_params:
    learning_rate: 0.001
scheduler:
  name: CosineAnnealingLR
  hyper_params:
    T_max: 20
    eta_min: 0.0000001
    last_epoch: -1
loss_function: 
  name: mean-squared-error-loss
