mode: eval
dataset: 
  name: fgvc7
  has_additional_files: True
  additional_files_path: images
  fold: 0
  resize_dims: 224
model: 
  name: efficientnet-b7
  num_classes: 4
  hyper_params:
    batch_norm_momentum:  0.99
