mode: train
seed: 512
validation_frequency: 2
epochs: 30
batch_size: 8
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 2
  resize_dims: 575
  transform: policy
val_dataset: 
  name: fgvc7
  fold: 2
  resize_dims: 575
model: 
  name: efficientnet-b5
  pred_type: classification
  tuning_type: fine-tuning
  hyper_params:
    fc_drop_out: 0.5
  pre_trained_path: exp_27_c
optimiser: 
  name: AdamW
  hyper_params:
    learning_rate: 0.0008
    weight_decay: 0.0001
scheduler:
  name: cosineAnnealing-warmup-lr
loss_function: 
  name: cross-entropy-loss
