mode: train
seed: 1024
validation_frequency: 2
epochs: 100
batch_size: 10
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 0
  resize_dims: 320
  transform: policy
val_dataset: 
  name: fgvc7
  fold: 0
  resize_dims: 320
model: 
  name: efficientnet-b4
  pred_type: classification
  tuning_type: fine-tuning
  hyper_params:
    batch_norm_momentum: 0.99
optimiser: 
  name: AdamW
  hyper_params:
    learning_rate: 0.001
scheduler:
  name: CosineAnnealingLR
  hyper_params:
    T_max: 100
    eta_min: 0.000000001
    last_epoch: -1
loss_function: 
  name: arcface-loss
