experiment_name: experiment_1
validation_frequency: 5
epochs: 400
batch_size: 8
dataset: 
  name: fgvc7
  has_additional_files: True
  additional_files_path: images
  fold: 2
  resize_dims: 224
model: 
  name: densenet-161
optimiser: 
  name: RMSprop
  hyper_params:
    decay: 0.9
    momentum: 0.9
    batch_norm_momentum:  0.99
    weight_decay: 0.00001
    learning_rate: 0.256
    centered: False
loss_function: 
  name: 'cross-entropy-loss'

