mode: test
test_dataset: 
  name: fgvc7
  resize_dims: 512
ensemble: False
num_classes: 4
model_list:
  - model:
      path: train_b_1
      name: efficientnet-b7
      pred_type: regression
      hyper_params:
        batch_norm_momentum:  0.99
  - model:
      path: train_b_2
      name: efficientnet-b7
      pred_type: regression
      hyper_params:
        batch_norm_momentum:  0.99