mode: test
seed: 512
test_dataset: 
  name: fgvc7
  resize_dims: 545
  transform: image
  tta: True
ensemble: True
num_classes: 4
experiment_list:
  - experiment:
      path: exp_32_a
#   - experiment:
#       path: exp_32_b
#   - experiment:
#       path: exp_32_c
#   - experiment:
#       path: exp_32_d
#   - experiment:
#       path: exp_32_e