mode: test
test_dataset: 
  name: fgvc7
  resize_dims: 256
ensemble: False
num_classes: 4
experiment_list:
  - experiment:
      path: b4_11
      weight_type: best_val_roc
  - experiment:
      path: b4_12
      weight_type: best_val_roc
      resize_dims: original