mode: test
seed: 1024
test_dataset: 
  name: fgvc7
  resize_dims: 320
ensemble: True
num_classes: 4
experiment_list:
  - experiment:
      path: exp_22_a
      weight_type: best_val_roc
  - experiment:
      path: exp_22_b
      weight_type: best_val_roc