mode: test
test_dataset: 
  name: fgvc7
  resize_dims: 224
ensemble: False
model_list:
  - model:
      name: efficientnet-b7
      num_classes: 4
      path: train_1
      hyper_params:
        batch_norm_momentum:  0.99
  - model:
      name: densenet-161
      num_classes: 4
      path: train_2