mode: test
seed: 1024
test_dataset: 
  name: fgvc7
  resize_dims: 224
ensemble: True
num_classes: 4
experiment_list:
  - experiment:
      path: train_dummy_1
  # - experiment:
  #     path: train_dummy_2
  #     weight_type: best_val_roc