mode: train
validation_frequency: 5
epochs: 400
batch_size: 4
train_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 224
val_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 224
model: 
  name: efficientnet-b7
  num_classes: 4
  hyper_params:
    batch_norm_momentum:  0.99
optimiser: 
  name: RMSprop
  hyper_params:
    momentum: 0.9
    weight_decay: 0.00001
    learning_rate: 0.256
    centered: False
scheduler:
  name: StepLR
  hyper_params:
    lr_decay: 0.97
    step: 4
loss_function: 
  name: 'cross-entropy-loss'
