mode: train
validation_frequency: 2
epochs: 50
batch_size: 4
train_dataset: 
  name: fgvc7
  fold: 3
  resize_dims: 224
val_dataset: 
  name: fgvc7
  fold: 3
  resize_dims: 224
model: 
  name: efficientnet-b7
  pred_type: regression
  num_classes: 4
  tuning_type: feature-extraction
  hyper_params:
    batch_norm_momentum:  0.99
optimiser: 
  name: Adam
  hyper_params:
    learning_rate: 0.005
scheduler:
  name: CosineAnnealingLR
  hyper_params:
    T_max: 50
    eta_min: 0.0001
    last_epoch: -1
loss_function: 
  name: mean-squared-error-loss
