mode: train
validation_frequency: 1
epochs: 1
batch_size: 128
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 4
  resize_dims: 180
val_dataset: 
  name: fgvc7
  fold: 4
  resize_dims: 180
model: 
  name: efficientnet-b4
  pred_type: classification
  tuning_type: feature-extraction
  hyper_params:
    batch_norm_momentum:  0.99
optimiser: 
  name: AdamW
  hyper_params:
    learning_rate: 0.001
scheduler:
  name: CosineAnnealingLR
  hyper_params:
    T_max: 1
    eta_min: 0.0000001
    last_epoch: -1
loss_function: 
  name: arcface-loss