mode: train
validation_frequency: 2
epochs: 50
batch_size: 128
train_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 224
val_dataset: 
  name: fgvc7
  fold: 1
  resize_dims: 224
model: 
  name: densenet-161
  num_classes: 4
  tuning_type: 'feature-extraction'
optimiser: 
  name: RMSprop
  hyper_params:
    momentum: 0.0
    weight_decay: 0.0
    learning_rate: 0.001
    centered: False
loss_function: 
  name: 'negative-log-likelihood-loss'
