mode: train
validation_frequency: 5
epochs: 50
batch_size: 4
num_classes: 4
train_dataset: 
  name: fgvc7
  fold: 0
  resize_dims: 128
val_dataset: 
  name: fgvc7
  fold: 0
  resize_dims: 128
model: 
  name: efficientnet-b7
  pred_type: regression
  tuning_type: feature-extraction
  hyper_params:
    batch_norm_momentum:  0.99
optimiser: 
  name: AdamW
  hyper_params:
    learning_rate: 0.001
scheduler:
  name: CosineAnnealingLR
  hyper_params:
    T_max: 2
    eta_min: 0.0000001
    last_epoch: -1
loss_function: 
  name: mean-squared-error-loss
