wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.32
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
batch_size:
  desc: null
  value: 8
best_val_loss:
  desc: null
  value: 1.7541704177856445
best_val_roc:
  desc: null
  value: 0.9633904539769587
epochs:
  desc: null
  value: 50
experiment_name:
  desc: null
  value: exp_21
learning_rate:
  desc: null
  value: 0.0005
loss_function:
  desc: null
  value: arcface-loss
model:
  desc: null
  value: efficientnet-b5
optimiser:
  desc: null
  value: AdamW
prediction_type:
  desc: null
  value: classification
resize_dims:
  desc: null
  value: 320
seed:
  desc: null
  value: 1024
