wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.32
    code_path: code/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.4
batch_size:
  desc: null
  value: 10
best_kaggle_metric:
  desc: null
  value: 0.982500658401888
best_val_loss:
  desc: null
  value: 0.4299169182777405
epochs:
  desc: null
  value: 100
experiment_name:
  desc: null
  value: exp_23_c
learning_rate:
  desc: null
  value: 0.001
loss_function:
  desc: null
  value: arcface-loss
model:
  desc: null
  value: efficientnet-b4
optimiser:
  desc: null
  value: AdamW
prediction_type:
  desc: null
  value: classification
resize_dims:
  desc: null
  value: 320
seed:
  desc: null
  value: 1024
